apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappp
  labels:
    app: myappp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: larryinit/myapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
