# Number of pod replicas
replicaCount: 2

# Container image settings
image:
  repository: larryinit/myapp
  tag: latest
  pullPolicy: Always

# Service settings
service:
  type: NodePort
  port: 80
  nodePort: 30080  # optional: choose a fixed port if you want

# Optional name overrides (keep empty unless you want to customize)
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
      paths:
        - path: /
          pathType: Prefix
  tls: []  # e.g., if you add HTTPS later
